In [3]:
%pylab qt

Populating the interactive namespace from numpy and matplotlib


In [4]:
from region.image import Image
from utils import *
import numpy

# Utils

In [5]:
class Image6a(Image):
    def setPts(self, pts, ptsSetup, withCorners=True):
        if withCorners:
            pts = np.vstack((pts, Image.getCorners(self.imArr)))
        self.pts = pts
        self.ptsSetup = ptsSetup
        return self.pts

    def setInputPts(self, ptSetup, withCorners=True):
        ptsCt = sum([x for x in ptSetup.values()])
        pts = np.array(getPoints(self, ptsCt))
        self.setPts(pts, ptSetup, withCorners)
        return self.pts

In [6]:
def getPoints(im, n):
    n = int(n)
    plt.imshow(im.imArr)
    points = plt.ginput(n, timeout = 300, show_clicks=True)
    plt.close()
    print("Points gotten from", im.name, ":", str(points))
    return np.array(points)

def dispPtsOnImg(im, results):
    plt.imshow(im)
    plt.plot(results[:, 0], results[:, 1], 'bo')
    for ind, tup in enumerate(results):
        x, y = tup
        plt.text(x, y, str(ind))
#     for x, y in results:
#         plt.text(x, y, "%d-%d" % (x,y))
    plt.waitforbuttonpress()
    plt.close()

In [ ]:
imT1 = Image.fromPath("../sample_imgs/20181103_162858.jpg")

In [ ]:
viewImage(imT1.imArr)

In [20]:
def computeH(im1Pts, im2Pts):
    assert len(im1Pts) == len(im2Pts)
    A = createA(im1Pts, im2Pts)
    print("A:\n", A)
    b = np.zeros(len(A))
    b[-1] = 1
    print("b:\n", b)
    
    x = numpy.linalg.lstsq(A, b)
    return x

In [22]:
computeH(im1Pts[:4], im2Pts[:4])

A:
 [[-5.150000e+02 -1.477000e+03 -1.000000e+00  0.000000e+00  0.000000e+00
   0.000000e+00  9.841650e+05  2.822547e+06  1.911000e+03]
 [ 0.000000e+00  0.000000e+00  0.000000e+00 -5.150000e+02 -1.477000e+03
  -1.000000e+00  7.101850e+05  2.036783e+06  1.379000e+03]
 [-5.140000e+02 -1.732000e+03 -1.000000e+00  0.000000e+00  0.000000e+00
   0.000000e+00  9.807120e+05  3.304656e+06  1.908000e+03]
 [ 0.000000e+00  0.000000e+00  0.000000e+00 -5.140000e+02 -1.732000e+03
  -1.000000e+00  8.301100e+05  2.797180e+06  1.615000e+03]
 [-3.330000e+02 -1.668000e+03 -1.000000e+00  0.000000e+00  0.000000e+00
   0.000000e+00  5.700960e+05  2.855616e+06  1.712000e+03]
 [ 0.000000e+00  0.000000e+00  0.000000e+00 -3.330000e+02 -1.668000e+03
  -1.000000e+00  5.134860e+05  2.572056e+06  1.542000e+03]
 [-6.910000e+02 -1.619000e+03 -1.000000e+00  0.000000e+00  0.000000e+00
   0.000000e+00  1.420696e+06  3.328664e+06  2.056000e+03]
 [ 0.000000e+00  0.000000e+00  0.000000e+00 -6.910000e+02 -1.619000e+03
  -1.00

/Users/reginaongowarsito/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  if __name__ == '__main__':


(array([ 2.05046327e+00, -5.02168372e-01,  1.48695284e+03,  1.02541905e+00,
         4.53880955e-01,  1.01322008e+02,  6.31609094e-04, -2.59116614e-04,
         1.00000000e+00]),
 array([], dtype=float64),
 9,
 array([8.31873815e+06, 6.24047895e+05, 3.40850674e+03, 3.06520776e+02,
        2.56405675e+02, 5.83947774e+01, 1.20313667e+01, 5.93707943e-03,
        6.70279260e-04]))

In [14]:
def createA(im1Pts, im2Pts):
    result = np.zeros((len(im1Pts) * 2 + 1, 9))
    for i in range(len(im1Pts)):
        im1Point = im1Pts[i]
        im2Point = im2Pts[i]
        
        # first row set
        result[i*2, 0] = -1 * im1Point[0]
        result[i*2, 1] = -1 * im1Point[1]
        result[i*2, 2] = -1
        
        result[i*2, 6] = im1Point[0] * im2Point[0]
        result[i*2, 7] = im1Point[1] * im2Point[0]
        result[i*2, 8] = im2Point[0]
        
        
        # second row set
        result[i*2+1, 3] = -1 * im1Point[0]
        result[i*2+1, 4] = -1 * im1Point[1]
        result[i*2+1, 5] = -1
        
        result[i*2+1, 6] = im1Point[0] * im2Point[1]
        result[i*2+1, 7] = im1Point[1] * im2Point[1]
        result[i*2+1, 8] = im2Point[1]
    result[-1, -1] = 1
    
    return result
    

# def createA(numOfPts):
#     result = np.zeros((numOfPts * 2, 8))
    
#     for i in range()

In [10]:
imSproul0 = Image.fromPath("../curated_sample_imgs/lower_sproul/lower_sproul_00.jpg")

/Users/reginaongowarsito/anaconda3/lib/python3.6/site-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "


In [ ]:
dispPtsOnImg(imSproul0.imArr, im1Pts)

In [15]:
im1Pts = np.array([[515, 1477], [514, 1732], [333, 1668], [691, 1619], [791, 1605], [1286, 1535], [2038, 1408], [2032, 1528]])
im2Pts = np.array([[1911, 1379], [1908, 1615], [1712, 1542], [2056, 1519], [2140, 1515], [2598, 1488], [3430, 1416], [3421, 1545]])
# im1Pts = np.array([])
# im2Pts = np.array([])
createA(im1Pts, im2Pts)

array([[-5.150000e+02, -1.477000e+03, -1.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  9.841650e+05,  2.822547e+06,
         1.911000e+03],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00, -5.150000e+02,
        -1.477000e+03, -1.000000e+00,  7.101850e+05,  2.036783e+06,
         1.379000e+03],
       [-5.140000e+02, -1.732000e+03, -1.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  9.807120e+05,  3.304656e+06,
         1.908000e+03],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00, -5.140000e+02,
        -1.732000e+03, -1.000000e+00,  8.301100e+05,  2.797180e+06,
         1.615000e+03],
       [-3.330000e+02, -1.668000e+03, -1.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  5.700960e+05,  2.855616e+06,
         1.712000e+03],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00, -3.330000e+02,
        -1.668000e+03, -1.000000e+00,  5.134860e+05,  2.572056e+06,
         1.542000e+03],
       [-6.910000e+02, -1.619000e+03, -1